/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashSettingsRouteImport } from './routes/dash/settings'
import { Route as DashTunnelsIndexRouteImport } from './routes/dash/tunnels/index'
import { Route as DashTunnelsTunnelIdRouteImport } from './routes/dash/tunnels/$tunnelId'
import { Route as ApiTunnelCheckSubdomainRouteImport } from './routes/api/tunnel/check-subdomain'
import { Route as ApiTunnelAuthRouteImport } from './routes/api/tunnel/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/dash/settings',
  path: '/dash/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashTunnelsIndexRoute = DashTunnelsIndexRouteImport.update({
  id: '/dash/tunnels/',
  path: '/dash/tunnels/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashTunnelsTunnelIdRoute = DashTunnelsTunnelIdRouteImport.update({
  id: '/dash/tunnels/$tunnelId',
  path: '/dash/tunnels/$tunnelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelCheckSubdomainRoute = ApiTunnelCheckSubdomainRouteImport.update({
  id: '/api/tunnel/check-subdomain',
  path: '/api/tunnel/check-subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelAuthRoute = ApiTunnelAuthRouteImport.update({
  id: '/api/tunnel/auth',
  path: '/api/tunnel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/dash/tunnels/': typeof DashTunnelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash/settings'
    | '/dash'
    | '/api/auth/$'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/dash/tunnels/$tunnelId'
    | '/dash/tunnels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dash/settings'
    | '/dash'
    | '/api/auth/$'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/dash/tunnels/$tunnelId'
    | '/dash/tunnels'
  id:
    | '__root__'
    | '/'
    | '/dash/settings'
    | '/dash/'
    | '/api/auth/$'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/dash/tunnels/$tunnelId'
    | '/dash/tunnels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashIndexRoute: typeof DashIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTunnelAuthRoute: typeof ApiTunnelAuthRoute
  ApiTunnelCheckSubdomainRoute: typeof ApiTunnelCheckSubdomainRoute
  DashTunnelsTunnelIdRoute: typeof DashTunnelsTunnelIdRoute
  DashTunnelsIndexRoute: typeof DashTunnelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/settings': {
      id: '/dash/settings'
      path: '/dash/settings'
      fullPath: '/dash/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/tunnels/': {
      id: '/dash/tunnels/'
      path: '/dash/tunnels'
      fullPath: '/dash/tunnels'
      preLoaderRoute: typeof DashTunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/tunnels/$tunnelId': {
      id: '/dash/tunnels/$tunnelId'
      path: '/dash/tunnels/$tunnelId'
      fullPath: '/dash/tunnels/$tunnelId'
      preLoaderRoute: typeof DashTunnelsTunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/check-subdomain': {
      id: '/api/tunnel/check-subdomain'
      path: '/api/tunnel/check-subdomain'
      fullPath: '/api/tunnel/check-subdomain'
      preLoaderRoute: typeof ApiTunnelCheckSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/auth': {
      id: '/api/tunnel/auth'
      path: '/api/tunnel/auth'
      fullPath: '/api/tunnel/auth'
      preLoaderRoute: typeof ApiTunnelAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashIndexRoute: DashIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTunnelAuthRoute: ApiTunnelAuthRoute,
  ApiTunnelCheckSubdomainRoute: ApiTunnelCheckSubdomainRoute,
  DashTunnelsTunnelIdRoute: DashTunnelsTunnelIdRoute,
  DashTunnelsIndexRoute: DashTunnelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
